name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: Describe the feature you'd like to see.
      placeholder: What feature would you like to see?
      value: "
# Summary
- summarize your feature suggestion.

# Problem / Reason:
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

# Solution
A clear and concise description of what you want to happen.

# Details
"
    validations:
      required: true

